package token;

public enum TokName {
	NOT, NOTEQUAL, 
	LBRACE, RBRACE,
	MULTEQUAL, MULT,
	PLUSPLUS, PLUSEQUAL, PLUS,		//++, +=, +,
	COMMA, DOT, COLON, SEMICOLON,
	QUESTMARK,
	LBRACK, RBRACK, 
	LPAREN, RPAREN, 
	TILDE,
	SLASHSLASH, SLASHEQUAL, SLASH, // /=, /
	LESSLESSEQUAL, LESSLESS, LESSEQUAL, LESS, // <<=, <<, <=, <,
	EQUALEQUAL, EQUAL, // ==, =
	GTGTGTEQUAL, GTGTGT, GTGTEQUAL, GTGT, GTEQUAL, GT, // >>>=, >>>, >>=, >>, >=, >,
	PERCENTEQUAL, PERCENT, //%=, %
	ANDEQUAL, ANDAND, AND, // &=, &&, &,
	EXPEQUAL, EXP, // ^=, ^,
	OREQUAL, OROR, OR, //|=, ||, |
	MINUSEQUAL, MINUSMINUS, MINUS, //-=, --, -,
	INTEGERLITERAL,
	IDENTIFIER,
	EOF,
	KEYWORD
}
